---
- name: Provision hcloud infrastructure 
  hosts: localhost
  gather_facts: false

  module_defaults:
    group/hetzner.hcloud.all:
      api_token: "{{ lookup('ansible.builtin.unvault', 'hcloud.token') | string | trim }}"

  roles:
    - hcloud
