---
- name: Create default firewall
  hetzner.hcloud.firewall:
    name: default
    labels:
      key: default
      value: ""
    rules:
      - description: Allow icmp from everywhere
        direction: in
        protocol: icmp
        source_ips:
          - 0.0.0.0/0
          - ::/0
      - description: Allow http inbound traffic
        direction: in
        protocol: tcp
        source_ips:
          - 0.0.0.0/0
          - ::/0
        port: "80"
      - description: Allow https inbound traffic
        direction: in
        protocol: tcp
        source_ips:
          - 0.0.0.0/0
          - ::/0
        port: "443"
      - description: Allow ssh inbound traffic
        direction: in
        protocol: tcp
        source_ips:
          - 0.0.0.0/0
          - ::/0
        port: "22"
    state: present
