---
- name: Create Primary IP
  hetzner.hcloud.primary_ip:
    name: "{{ item }}"
    labels:
      key: default
      value: ""
    type: "{{ item }}"
    datacenter: nbg1-dc3
    auto_delete: false
    delete_protection: true
    state: present
  loop:
    - ipv4
    - ipv6
